ddns:
  server: api-ipv4.dynu.com
  port: 8245
  protocol: http
  path: /nic/update
  last_ip: 0.0.0.0
  users:
    - username: kinist
      password: k+qr3C@3CV7V#yv
    - username: mycsgbz8
      password: k+qr3C@3CV7V#yv  
  # 自动更新频率（使用crontab格式）
  # 格式：分钟 小时 日期 月份 星期
  # 示例：
  #   "*/5 * * * *"    - 每5分钟执行一次
  #   "0 * * * *"      - 每小时整点执行
  #   "0 */2 * * *"    - 每2小时执行一次
  #   "0 0 * * *"      - 每天午夜执行
  #   "0 9,17 * * *"   - 每天9点和17点执行
  #   "0 0 * * 0"      - 每周日午夜执行
  #   "0 0 1 * *"      - 每月1号午夜执行
  schedule: '*/1 * * * *'
smtp:
  server: mail.sohu.com
  port: 465
  username: kinist@sohu.com
  password: FU6OAE175Y3
  sender: kinist@sohu.com
  receiver: kinist@qq.com
  use_tls: false